name: ci

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: Install dependencies
        run: |
          make init-dev
      - name: Lint with flake8
        run: |
          make lint-flake8
      - name: Lint with black
        run: |
          make lint-black
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: Install dependencies
        run: |
          make init-dev
      - name: Run Tests
        run: |
          make test